name: Java CI Pipeline

on:
  push:
    branches: [ main, enhancement/ci, feature/test_automation ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant gradlew permissions
      run: chmod +x gradlew

    - name: Cache Gradle dependencies
      uses: actions/cache@v3  
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install dependencies for Chrome and headless browser
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          google-chrome-stable \
          chromium-chromedriver \
          libx11-xcb1 \
          libfontconfig1 \
          libxcomposite1 \
          libxrandr2 \
          libgtk-3-0 \
          libgbm-dev \
          wget

    - name: Verify Chrome installation
      run: |
        google-chrome-stable --version
        chromedriver --version

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose-plugin

    - name: Build Docker image
      run: docker build -t beluga-asg .

    - name: Start Docker Compose
      run: docker compose -f docker-compose.yml up -d

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        until nc -z -v -w30 localhost 5432; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done
        echo "PostgreSQL is ready."

    - name: Run Integration Tests
      run: ./gradlew integrationTest

    - name: Stop Docker Compose
      if: always()
      run: docker compose -f docker-compose.yml down

    - name: Clean up Docker images and containers
      run: |
        docker system prune -af