name: CI Pipeline

on:
  push:
    branches: [ main, enhancement/ci ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Generate Code Coverage Report (JaCoCo)
      run: ./gradlew jacocoTestReport

    - name: Upload JUnit Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-reports
        path: build/reports/tests/test/

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: build/reports/jacoco/test/html/

    - name: Build Docker Image
      run: |
        docker build -t beluga-test:latest .

    - name: Run Docker Container
      run: |
        docker run --rm beluga-test:latest