name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          dependencies-cache-key: |
            **/*.gradle
            **/gradle.properties
            gradle-wrapper.properties

      - name: Run tests and generate coverage
        run: ./gradlew test jacocoTestReport

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/reports/jacoco/

      - name: Archive coverage HTML
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-html
          path: build/reports/jacoco/jacocoTestReport/html/

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t beluga-test:latest .

      - name: Run container tests
        run: |
          docker run --rm beluga-test:latest ./gradlew test